import { Product } from "./types";

export const products: Product[] = [
  // ── Collection 1 : Confort & Repos ──────────────────────────────
  {
    slug: "arbre-a-chat-premium",
    name: "Arbre à Chat Premium Multi-Niveaux",
    price: 79.90,
    category: "Confort & Repos",
    collection: "Confort & Repos",
    badge: "BESTSELLER",
    sizes: ["S", "M", "L"],
    images: ["/products/jean-1-a.avif", "/products/jean-1-b.jpg"],
    description: "Arbre à chat robuste avec plateformes, griffoirs en sisal naturel et nichoir douillet. Idéal pour les chats actifs qui aiment grimper, griffer et observer.",
    details: {
      dimensions: "50 × 50 × 120 cm (L)",
      matiere: "Bois MDF + peluche + sisal naturel",
      poids: "6,5 kg",
      convient_pour: "Chats jusqu'à 8 kg",
      entretien: "Nettoyage à la brosse douce",
      garantie: "1 an pièces et main-d'œuvre",
    },
    styleWith: ["Jouet plume télescopique", "Balle distributrice", "Tunnel d'éveil"],
  },
  {
    slug: "coussin-orthopedique-chien",
    name: "Coussin Orthopédique Mémoire de Forme pour Chien",
    price: 49.90,
    category: "Confort & Repos",
    collection: "Confort & Repos",
    badge: "NOUVEAU",
    sizes: ["S", "M", "L"],
    images: ["/products/jean-2-a.webp", "/products/jean-2-b.webp"],
    description: "Coussin orthopédique en mousse à mémoire de forme pour soulager les articulations de votre chien. Housse déhoussable et lavable en machine.",
    details: {
      dimensions: "60 × 45 cm (M)",
      matiere: "Mousse à mémoire de forme + microfibre",
      poids: "1,2 kg",
      convient_pour: "Chiens de 5 à 25 kg",
      entretien: "Housse lavable à 30°C",
      garantie: "6 mois",
    },
    styleWith: ["Gamelle inox", "Harnais de promenade"],
  },
  {
    slug: "panier-douillet-chat",
    name: "Panier Douillet Moelleux pour Chat",
    price: 39.90,
    category: "Confort & Repos",
    collection: "Confort & Repos",
    badge: "NOUVEAU",
    sizes: ["S", "M"],
    images: ["/products/jean-3-a.jpg", "/products/jean-3-b.jpg"],
    description: "Panier ultra-doux en peluche longue avec bords rembourrés. Votre chat peut s'y lover confortablement. Fond antidérapant pour une stabilité totale.",
    details: {
      dimensions: "45 × 45 × 20 cm (M)",
      matiere: "Peluche longue + fond antidérapant",
      poids: "0,7 kg",
      convient_pour: "Chats jusqu'à 6 kg",
      entretien: "Lavable en machine à 30°C",
      garantie: "6 mois",
    },
    styleWith: ["Arbre à chat premium", "Jouet plume télescopique"],
  },
  {
    slug: "hamac-mural-chat",
    name: "Hamac Mural Suspendu pour Chat",
    price: 34.90,
    category: "Confort & Repos",
    collection: "Confort & Repos",
    badge: null,
    sizes: ["Unique"],
    images: ["/products/jean-4-a.webp", "/products/jean-4-b.webp"],
    description: "Hamac mural à fixer sur les radiateurs ou sous une fenêtre. Structure solide en métal, tissu résistant et confortable. Idéal pour les chats qui aiment observer.",
    details: {
      dimensions: "55 × 38 cm",
      matiere: "Métal + tissu Oxford renforcé",
      poids: "0,5 kg",
      convient_pour: "Chats jusqu'à 8 kg",
      entretien: "Tissu amovible lavable à 30°C",
      garantie: "1 an",
    },
    styleWith: ["Panier douillet", "Arbre à chat premium"],
  },

  // ── Collection 2 : Jeux & Éveil ──────────────────────────────────
  {
    slug: "jouet-plume-telescopique",
    name: "Canne à Pêche Plume Télescopique Interactive",
    price: 14.90,
    category: "Jeux & Éveil",
    collection: "Jeux & Éveil",
    badge: "BESTSELLER",
    sizes: ["Unique"],
    images: ["/products/jean-5-a.jpg", "/products/jean-5-b.jpg"],
    description: "Canne à pêche télescopique 60 cm avec plumes colorées et grelot. Stimule l'instinct chasseur de votre chat pour des sessions de jeu intenses et enrichissantes.",
    details: {
      dimensions: "60 cm déployée",
      matiere: "Plastique ABS + plumes naturelles",
      poids: "80 g",
      convient_pour: "Chats de tous âges",
      entretien: "Essuyage avec chiffon humide",
      garantie: "3 mois",
    },
    styleWith: ["Tunnel d'éveil", "Balle distributrice"],
  },
  {
    slug: "tunnel-eveil-chat",
    name: "Tunnel d'Éveil Pliable 3 Entrées pour Chat",
    price: 22.90,
    category: "Jeux & Éveil",
    collection: "Jeux & Éveil",
    badge: "NOUVEAU",
    sizes: ["Unique"],
    images: ["/products/jean-6-a.jpg", "/products/jean-6-b.jpg"],
    description: "Tunnel en S avec 3 entrées, feuilles froissantes et fenêtre centrale. Se plie en un instant pour ranger. Parfait pour les chats qui adorent se cacher et bondir.",
    details: {
      dimensions: "90 × 25 cm déployé",
      matiere: "Polyester renforcé + armature spiralée",
      poids: "200 g",
      convient_pour: "Chats de tous âges",
      entretien: "Nettoyage brosse douce",
      garantie: "3 mois",
    },
    styleWith: ["Jouet plume télescopique", "Balle distributrice"],
  },
  {
    slug: "corde-noeuds-chien",
    name: "Corde à Nœuds Résistante pour Chien",
    price: 12.90,
    category: "Jeux & Éveil",
    collection: "Jeux & Éveil",
    badge: null,
    sizes: ["S", "M", "L"],
    images: ["/products/jean-7-a.avif"],
    description: "Corde de jeu en coton naturel tressé avec gros nœuds. Idéale pour les jeux de traction, les mordillements et le renforcement de la relation maître-chien.",
    details: {
      dimensions: "40 cm (M)",
      matiere: "Coton naturel tressé",
      poids: "180 g (M)",
      convient_pour: "Chiens de toutes tailles",
      entretien: "Lavable en machine à 30°C",
      garantie: "3 mois",
    },
    styleWith: ["Harnais de promenade", "Laisse extensible"],
  },
  {
    slug: "balle-distributrice",
    name: "Balle Distributrice de Friandises Interactive",
    price: 19.90,
    category: "Jeux & Éveil",
    collection: "Jeux & Éveil",
    badge: null,
    sizes: ["Unique"],
    images: ["/products/jean-8-a.jpg", "/products/jean-8-b.jpg"],
    description: "Balle en caoutchouc naturel avec ouverture réglable pour y glisser des friandises. Stimule l'intelligence de votre chien et l'occupe pendant de longues heures.",
    details: {
      dimensions: "Ø 8 cm",
      matiere: "Caoutchouc naturel non toxique",
      poids: "150 g",
      convient_pour: "Chiens de toutes tailles",
      entretien: "Lavage à l'eau savonneuse",
      garantie: "3 mois",
    },
    styleWith: ["Corde à nœuds", "Gamelle inox"],
  },

  // ── Collection 3 : Quotidien & Soins ─────────────────────────────
  {
    slug: "gamelle-inox-antiderapante",
    name: "Gamelle Double Inox Antidérapante",
    price: 24.90,
    category: "Quotidien & Soins",
    collection: "Quotidien & Soins",
    badge: "BESTSELLER",
    sizes: ["S", "M", "L"],
    images: ["/products/jean-1-b.jpg", "/products/jean-1-c.jpg"],
    description: "Set de 2 gamelles en inox 304 alimentaire avec support surélevé en bois et semelles antidérapantes. Design épuré, facile à nettoyer, résistant à la rouille.",
    details: {
      dimensions: "Support 30 × 15 × 10 cm (M)",
      matiere: "Inox 304 + bois naturel",
      poids: "400 g",
      convient_pour: "Chats et chiens",
      entretien: "Compatible lave-vaisselle",
      garantie: "2 ans",
    },
    styleWith: ["Fontaine filtrante", "Coussin orthopédique"],
  },
  {
    slug: "fontaine-filtrante",
    name: "Fontaine Filtrante Silencieuse 2,5L",
    price: 44.90,
    category: "Quotidien & Soins",
    collection: "Quotidien & Soins",
    badge: "PREMIUM",
    sizes: ["Unique"],
    images: ["/products/jean-2-a.webp"],
    description: "Fontaine filtrante 2,5L ultra-silencieuse avec triple filtration au charbon actif. Incite votre animal à boire plus et prévient les problèmes rénaux.",
    details: {
      dimensions: "22 × 18 × 20 cm",
      matiere: "ABS alimentaire + filtre charbon actif",
      poids: "620 g (vide)",
      convient_pour: "Chats et chiens",
      entretien: "Nettoyage hebdomadaire, filtre /mois",
      garantie: "1 an",
    },
    styleWith: ["Gamelle inox", "Panier douillet"],
  },
  {
    slug: "harnais-promenade",
    name: "Harnais de Promenade Réglable Anti-Fugue",
    price: 27.90,
    category: "Quotidien & Soins",
    collection: "Quotidien & Soins",
    badge: null,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: ["/products/jean-3-a.jpg"],
    description: "Harnais en nylon respirant avec boucles de sécurité renforcées et poignée dorsale. Réglable sur 5 points pour un confort optimal. Anneau de laisse inox.",
    details: {
      dimensions: "Tour de poitrail 40–55 cm (M)",
      matiere: "Nylon respirant + boucles polypropylène",
      poids: "120 g (M)",
      convient_pour: "Chiens de toutes races",
      entretien: "Lavable en machine à 30°C",
      garantie: "1 an",
    },
    styleWith: ["Laisse extensible", "Corde à nœuds"],
  },
  {
    slug: "laisse-extensible",
    name: "Laisse Extensible 5m Grip Confort",
    price: 17.90,
    category: "Quotidien & Soins",
    collection: "Quotidien & Soins",
    badge: null,
    sizes: ["S", "M", "L"],
    images: ["/products/jean-4-a.webp"],
    description: "Laisse rétractable 5m avec mécanisme frein-blocage et poignée ergonomique antidérapante. Câble résistant. Idéale pour les promenades en liberté contrôlée.",
    details: {
      dimensions: "5 m de longueur",
      matiere: "ABS + câble nylon renforcé",
      poids: "220 g",
      convient_pour: "Chiens jusqu'à 50 kg (L)",
      entretien: "Essuyage avec chiffon humide",
      garantie: "1 an",
    },
    styleWith: ["Harnais de promenade", "Balle distributrice"],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getSimilarProducts(slug: string, count = 4): Product[] {
  return products.filter((p) => p.slug !== slug).slice(0, count);
}

export function getProductsByCollection(collection: string): Product[] {
  return products.filter((p) => p.collection === collection);
}

export const collections = ["Confort & Repos", "Jeux & Éveil", "Quotidien & Soins"];
