import { Product } from "./types";

const DC = (p: string) => `https://dog-and-cat-design.com/wp-content/uploads/${p}`;

export const products: Product[] = [
  // ── Collection 1 : Confort & Repos ──────────────────────────────
  {
    slug: "panier-classic-chien",
    name: "Panier Classic Graphite — Bowl & Bone",
    price: 139.90,
    category: "Confort & Repos",
    collection: "confort-repos",
    badge: "BESTSELLER",
    sizes: ["S", "M", "L", "XL"],
    images: [
      DC("2019/04/dog-bed-classic-graphite-bowlandbonerepublic-l1-600x534.webp"),
      DC("2019/04/dog-bed-classic-graphite-bowlandbonerepublic-l1-600x534.webp"),
      DC("2021/09/mc_mare_sand-1_recolored-min-600x600.jpg"),
    ],
    description: "Le panier Classic de Bowl & Bone Republic est un incontournable du design pour chien. Fabriqué à la main en Pologne, son tissu graphite ultra-résistant et sa doublure polaire moelleuse offrent un confort haut de gamme. Un objet de décoration autant qu'un nid douillet.",
    details: {
      dimensions: "65 × 50 cm (M)",
      matiere: "Tissu graphite + doublure polaire",
      poids: "1,2 kg",
      convient_pour: "Chiens de 5 à 20 kg",
      entretien: "Lavable en machine à 30°C",
      garantie: "1 an",
    },
    styleWith: ["Canapé-Lit COVO", "Coussin CORDO"],
  },
  {
    slug: "canape-covo-chien",
    name: "Canapé-Lit COVO — Miacara",
    price: 279.90,
    category: "Confort & Repos",
    collection: "confort-repos",
    badge: "EXCLUSIF",
    sizes: ["S", "M", "L"],
    images: [
      DC("2015/02/Covooooo-600x600.webp"),
      DC("2015/02/Covooooo-600x600.webp"),
      DC("2019/04/dog-bed-classic-graphite-bowlandbonerepublic-l1-600x534.webp"),
    ],
    description: "Le COVO de Miacara est un canapé-lit pour chien qui redéfinit le luxe. Structure en bois laqué blanc, coussin central en polyester recyclé ultra-doux, bolsters latéraux. Ce meuble design s'intègre dans les intérieurs les plus exigeants.",
    details: {
      dimensions: "80 × 60 cm (M)",
      matiere: "Bois laqué + polyester recyclé + mousse HR",
      poids: "5,5 kg",
      convient_pour: "Chiens de 5 à 30 kg",
      entretien: "Housse déhoussable lavable à 30°C",
      garantie: "2 ans",
    },
    styleWith: ["Panier Classic", "Tapis FOSSER"],
  },
  {
    slug: "panier-simone-feutre",
    name: "Panier SIMONE Laine Naturelle — Mishum",
    price: 89.90,
    category: "Confort & Repos",
    collection: "confort-repos",
    badge: "NOUVEAU",
    sizes: ["S", "M", "L"],
    images: [
      DC("2022/06/lit-design-chat-chien-feutre-laine-naturelle-3.jpg"),
      DC("2022/06/lit-design-chat-chien-feutre-laine-naturelle-3.jpg"),
      DC("2023/04/DSF5229_1024x10242x-1-600x600.jpg"),
    ],
    description: "Le panier SIMONE de Mishum est façonné en feutre de laine naturelle, 100% biodégradable. Sa forme arrondie et ses parois épaisses créent un cocon chaud et sécurisant pour chats et petits chiens. Chaque pièce est unique, fabriquée à la main par des artisans.",
    details: {
      dimensions: "Ø 50 cm (M)",
      matiere: "Feutre de laine naturelle 100%",
      poids: "0,8 kg",
      convient_pour: "Chats et chiens jusqu'à 8 kg",
      entretien: "Brossage doux, pas de machine",
      garantie: "1 an",
    },
    styleWith: ["Couverture TÖSSE", "Canapé COVO"],
  },
  {
    slug: "couverture-tosse-fourrure",
    name: "Couverture Imitation Fourrure TÖSSE — Labbvenn",
    price: 79.90,
    category: "Confort & Repos",
    collection: "confort-repos",
    badge: null,
    sizes: ["S", "M", "L"],
    images: [
      DC("2021/12/LABBVENN-TOSSE2.jpg"),
      DC("2021/12/LABBVENN-TOSSE2.jpg"),
      DC("2022/04/Copie-de-Copie-de-Publication-Instagram-France-sport-boxe-bleu-blanc-rouge-42-1-600x600.jpg"),
    ],
    description: "La couverture TÖSSE de Labbvenn est une pièce de confort ultime, en imitation fourrure d'une douceur incomparable. Réversible, ultra-moelleuse, elle s'installe sur un canapé, un panier ou directement au sol. Votre animal ne voudra plus la quitter.",
    details: {
      dimensions: "90 × 70 cm (M)",
      matiere: "Imitation fourrure + doublure microfibre",
      poids: "0,6 kg",
      convient_pour: "Chats et chiens",
      entretien: "Lavable en machine à 40°C",
      garantie: "1 an",
    },
    styleWith: ["Panier Classic", "Canapé COVO"],
  },

  // ── Collection 2 : Jeux & Éveil ──────────────────────────────────
  {
    slug: "arbre-chat-the-one",
    name: "Arbre à Chat Design THE ONE",
    price: 389.90,
    category: "Jeux & Éveil",
    collection: "jeux-eveil",
    badge: "BESTSELLER",
    sizes: ["Bois clair", "Bois sombre"],
    images: [
      DC("2023/09/THE-ONE--600x600.jpg"),
      DC("2023/09/THE-ONE--600x600.jpg"),
      DC("2021/02/MIKSTOWER_BENGAL-600x600.webp"),
    ],
    description: "THE ONE est l'arbre à chat qui conjugue architecture minimaliste et fonctionnalité maximale. Fabriqué en bois massif finition laquée, il offre plateformes, grotte et surface à gratter en sisal tressé à la main. Un meuble d'exception pour les chats qui méritent le meilleur.",
    details: {
      dimensions: "Ø 45 cm × H 160 cm",
      matiere: "Bois massif laqué + sisal tressé main",
      poids: "11 kg",
      convient_pour: "Chats de tous âges",
      entretien: "Brosse sisal douce",
      garantie: "2 ans",
    },
    styleWith: ["Griffoir CACTUS", "Panier SIMONE"],
  },
  {
    slug: "griffoir-cactus-bois",
    name: "Griffoir Design CACTUS en Bois",
    price: 79.90,
    category: "Jeux & Éveil",
    collection: "jeux-eveil",
    badge: null,
    sizes: ["Unique"],
    images: [
      DC("2015/02/4161-Griffoir-design-pour-chat-en-bois-CACTUS-600x600.jpg"),
      DC("2015/02/4161-Griffoir-design-pour-chat-en-bois-CACTUS-600x600.jpg"),
      DC("2024/01/lila-griffoir-mioou-chat-design-2-600x600.jpg"),
    ],
    description: "Le griffoir CACTUS est une sculpture fonctionnelle en bois massif et sisal naturel. Sa silhouette de cactus unique s'intègre dans tous les intérieurs et satisfait pleinement l'instinct de grattage de votre chat. Robuste, stable, il est fait pour durer.",
    details: {
      dimensions: "Ø 20 cm × H 55 cm",
      matiere: "Bois massif + sisal naturel",
      poids: "2,8 kg",
      convient_pour: "Chats de tous âges",
      entretien: "Brosse sèche",
      garantie: "1 an",
    },
    styleWith: ["Arbre à Chat THE ONE", "Panier SIMONE"],
  },
  {
    slug: "griffoir-tunnel-tito",
    name: "Griffoir Tunnel Fait Main TITO",
    price: 89.90,
    category: "Jeux & Éveil",
    collection: "jeux-eveil",
    badge: "NOUVEAU",
    sizes: ["Unique"],
    images: [
      DC("2021/05/TITO_DARK_GREY_lifestyle_6577_comp-600x600.jpg"),
      DC("2021/05/TITO_DARK_GREY_lifestyle_6577_comp-600x600.jpg"),
      DC("2023/05/loop-griffoir-chat-design-carton-3.jpg"),
    ],
    description: "Le griffoir TITO est un tunnel de jeu et de grattage fabriqué entièrement à la main. Sa forme tubulaire en sisal tressé invite votre chat à explorer, se cacher et griffer. Double fonction : griffoir et espace de jeu, pour stimuler l'instinct naturel de votre félin.",
    details: {
      dimensions: "L 60 × Ø 25 cm",
      matiere: "Sisal naturel tressé main + carton recyclé",
      poids: "1,4 kg",
      convient_pour: "Chats de tous âges",
      entretien: "Brosse sèche",
      garantie: "1 an",
    },
    styleWith: ["Arbre à Chat THE ONE", "Griffoir CACTUS"],
  },
  {
    slug: "panier-coco-labbvenn",
    name: "Nid Panier COCO — Labbvenn",
    price: 119.90,
    category: "Jeux & Éveil",
    collection: "jeux-eveil",
    badge: null,
    sizes: ["S", "M"],
    images: [
      DC("2021/08/coco-chien-labbvenn-1.jpg"),
      DC("2021/08/coco-chien-labbvenn-1.jpg"),
      DC("2021/08/LABBVENN-FOSSER-2.jpg"),
    ],
    description: "Le panier COCO de Labbvenn est un nid cocon à la fois espace de jeu et refuge sécurisant pour votre petit chien. Fabriqué à la main en tissu premium résistant, ses parois hautes et sa base souple procurent un environnement stimulant et rassurant.",
    details: {
      dimensions: "Ø 45 cm (S)",
      matiere: "Tissu premium + base mousse",
      poids: "0,7 kg",
      convient_pour: "Chiens jusqu'à 6 kg",
      entretien: "Lavable en machine à 30°C",
      garantie: "1 an",
    },
    styleWith: ["Couverture TÖSSE", "Tapis FOSSER"],
  },

  // ── Collection 3 : Quotidien & Soins ─────────────────────────────
  {
    slug: "coussin-cordo-velours",
    name: "Coussin CORDO Velours Côtelé",
    price: 74.90,
    category: "Quotidien & Soins",
    collection: "quotidien-soins",
    badge: "BESTSELLER",
    sizes: ["S", "M", "L", "XL"],
    images: [
      DC("2023/10/cordo-coussin-velours-pour-chien-min.jpg"),
      DC("2025/01/MC_2307_cord_01_low-res_36bf735b-68f6-41ae-9049-0aab4580cb34-600x600.webp"),
      DC("2023/10/cordo-coussin-velours-pour-chien-min.jpg"),
    ],
    description: "Le coussin CORDO en velours côtelé est l'accessoire quotidien par excellence. Sa structure ergonomique et son rembourrage en fibres recyclées offrent un soutien orthopédique optimal. Le velours côtelé, doux et résistant, est décliné en 8 coloris intemporels.",
    details: {
      dimensions: "70 × 50 cm (M)",
      matiere: "Velours côtelé + fibres recyclées",
      poids: "1,0 kg",
      convient_pour: "Chiens de toutes tailles",
      entretien: "Housse déhoussable lavable à 30°C",
      garantie: "1 an",
    },
    styleWith: ["Panier Classic", "Tapis FOSSER"],
  },
  {
    slug: "tapis-fosser-voyage",
    name: "Tapis de Voyage FOSSER — Labbvenn",
    price: 119.90,
    category: "Quotidien & Soins",
    collection: "quotidien-soins",
    badge: null,
    sizes: ["S", "M", "L"],
    images: [
      DC("2021/08/LABBVENN-FOSSER-2.jpg"),
      DC("2021/08/LABBVENN-FOSSER-2.jpg"),
      DC("2024/04/RAMPE-DESIGN-POUR-CHIEN-ET-CHAT-DOGBEAM.jpg"),
    ],
    description: "Le tapis FOSSER de Labbvenn est le compagnon de voyage idéal. Imperméable, anti-dérapant, ultra-léger et pliable en quelques secondes. Il se glisse dans n'importe quel sac et offre à votre chien une surface confortable partout : voiture, hôtel, chez des amis.",
    details: {
      dimensions: "80 × 55 cm (M)",
      matiere: "Microfibre imperméable + antidérapant",
      poids: "0,4 kg",
      convient_pour: "Chiens de toutes tailles",
      entretien: "Lavable en machine à 40°C",
      garantie: "1 an",
    },
    styleWith: ["Coussin CORDO", "Canapé COVO"],
  },
  {
    slug: "rampe-dogbeam",
    name: "Rampe Design DOGBEAM",
    price: 149.90,
    category: "Quotidien & Soins",
    collection: "quotidien-soins",
    badge: "EXCLUSIF",
    sizes: ["Unique"],
    images: [
      DC("2024/04/RAMPE-DESIGN-POUR-CHIEN-ET-CHAT-DOGBEAM.jpg"),
      DC("2024/04/RAMPE-DESIGN-POUR-CHIEN-ET-CHAT-DOGBEAM.jpg"),
      DC("2021/08/LABBVENN-FOSSER-2.jpg"),
    ],
    description: "La rampe DOGBEAM est pensée pour les chiens et chats qui ont du mal à monter sur le canapé ou le lit. Structure en bois massif laqué, surface antidérapante en textile, inclinaison optimale. Un accessoire quotidien indispensable habillé en meuble design.",
    details: {
      dimensions: "90 × 30 cm × H 40 cm",
      matiere: "Bois massif laqué + textile antidérapant",
      poids: "3,2 kg",
      convient_pour: "Chiens et chats jusqu'à 25 kg",
      entretien: "Essuyage chiffon humide",
      garantie: "2 ans",
    },
    styleWith: ["Canapé COVO", "Coussin CORDO"],
  },
  {
    slug: "panier-senso-box",
    name: "Panier Box SENSO — Miacara",
    price: 99.90,
    category: "Quotidien & Soins",
    collection: "quotidien-soins",
    badge: "NOUVEAU",
    sizes: ["S", "M", "L"],
    images: [
      DC("2025/01/MC_C02-020-02_Sleep_Senso_BoxBed_Pebble-Merle1-600x600.webp"),
      DC("2025/01/MC_C02-020-02_Sleep_Senso_BoxBed_Pebble-Merle1-600x600.webp"),
      DC("2023/10/cordo-coussin-velours-pour-chien-min.jpg"),
    ],
    description: "Le panier Box SENSO de Miacara allie praticité et élégance pour le quotidien. Ses parois rigides et son fond moelleux créent un espace définissable que votre animal peut s'approprier facilement. Idéal pour structurer l'espace de vie de votre compagnon tout au long de la journée.",
    details: {
      dimensions: "60 × 45 cm (M)",
      matiere: "Tissu Pebble-Merle + mousse haute densité",
      poids: "1,5 kg",
      convient_pour: "Chats et chiens jusqu'à 12 kg",
      entretien: "Housse lavable à 30°C",
      garantie: "1 an",
    },
    styleWith: ["Coussin CORDO", "Panier Classic"],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getSimilarProducts(slug: string, count = 4): Product[] {
  return products.filter((p) => p.slug !== slug).slice(0, count);
}

export function getProductsByCollection(collection: string): Product[] {
  return products.filter((p) => p.collection === collection);
}

export const collections = ["confort-repos", "jeux-eveil", "quotidien-soins"];
